defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: circleci/node:10.11.0

version: 2
jobs:
  npm-install:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~
      - checkout
      - restore_cache:
          key: node-modules-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install front dependencies
          command: npm install
      - save_cache:
          key: node-modules-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~
          paths:
            - repo

  frontend-tests:
    <<: *defaults
    environment:
      NODE_ENV: test
    steps:
      - attach_workspace:
          at: ~
      - run:
          name: Unit test with coverage
          command: npm run test:coverage
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  frontend:
    jobs:
      - npm-install
      - frontend-tests:
          requires:
            - npm-install
